export const APP_STATE = {
  currentSection: 'dashboard',
  currentSubSection: null,
  isAuthenticated: false,
  qboConnected: false,
  currentCustomer: null,
  currentProduct: null,
  customers: [],
  products: [],
  jobs: [],
  reports: {},
  // Existing import state (from original code)
  currentJobId: null,
  hasUnvalidatedChanges: false,
  csvHeaders: [],
  previewRows: [],
  mapping: {},
  currentValidation: {},
  overrideDuplicates: false,
  qboDuplicateOnlyRows: 0,
  lastDryRunSummary: null,
  lastDryRunRows: null
};
// QBO Fields (from original code, expanded)
export const QBO_FIELDS = [
  { value: "", label: "-- Not mapped --" },
  { value: "DisplayName", label: "DisplayName * (Required)" },
  { value: "CompanyName", label: "Company Name" },
  { value: "Title", label: "Title (Mr/Mrs)" },
  { value: "GivenName", label: "First Name" },
  { value: "MiddleName", label: "Middle Name" },
  { value: "FamilyName", label: "Last Name" },
  { value: "Suffix", label: "Suffix (Jr/Sr)" },
  { value: "PrintOnCheckName", label: "Print on Check As" },
  { value: "PrimaryEmailAddr.Address", label: "Primary Email" },
  { value: "WebAddr.URI", label: "Website" },
  { value: "PrimaryPhone.FreeFormNumber", label: "Primary Phone" },
  { value: "Mobile.FreeFormNumber", label: "Mobile Phone" },
  { value: "Fax.FreeFormNumber", label: "Fax" },
  { value: "AlternatePhone.FreeFormNumber", label: "Alternate Phone" },
  { value: "BillAddr.Line1", label: "Billing Address Line 1" },
  { value: "BillAddr.Line2", label: "Billing Address Line 2" },
  { value: "BillAddr.Line3", label: "Billing Address Line 3" },
  { value: "BillAddr.City", label: "Billing City" },
  { value: "BillAddr.CountrySubDivisionCode", label: "Billing State/Province" },
  { value: "BillAddr.PostalCode", label: "Billing ZIP/Postal" },
  { value: "BillAddr.Country", label: "Billing Country" },
  { value: "ShipAddr.Line1", label: "Shipping Address Line 1" },
  { value: "ShipAddr.Line2", label: "Shipping Address Line 2" },
  { value: "ShipAddr.City", label: "Shipping City" },
  { value: "ShipAddr.CountrySubDivisionCode", label: "Shipping State/Province" },
  { value: "ShipAddr.PostalCode", label: "Shipping ZIP/Postal" },
  { value: "ShipAddr.Country", label: "Shipping Country" },
  { value: "Notes", label: "Notes" },
  { value: "Taxable", label: "Taxable (true/false)" },
  { value: "Active", label: "Active (true/false)" },
  { value: "CurrencyRef.value", label: "Currency Code (e.g. USD)" }
];
// Product fields
export const PRODUCT_FIELDS = [
  { value: "Name", label: "Product/Service Name *" },
  { value: "Description", label: "Description" },
  { value: "UnitPrice", label: "Unit Price" },
  { value: "IncomeAccountRef", label: "Income Account" },
  { value: "ExpenseAccountRef", label: "Expense Account" },
  { value: "Type", label: "Type (Inventory/Service)" },
  { value: "PurchaseCost", label: "Purchase Cost" },
  { value: "QtyOnHand", label: "Quantity On Hand" },
  { value: "Taxable", label: "Taxable" },
  { value: "Active", label: "Active" }
];
export const AI_FIELDS = QBO_FIELDS;